# Generated by Django 3.1.5 on 2021-01-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirps',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
